<h1 style="text-align: center;"><strong>Ejercicios Extraclase - Avance 2</strong></h1>


<ul>
<li><strong>Curso:</strong> CE-1111: Análisis Númerico para Ingeniería</li>
<li><strong>Estudiante 1:</strong> Emanuel Chavarría Hernández </li>
    <li><strong>Estudiante 2:</strong> Randall Bolaños López</li>
</ul>




<strong>Pregunta 1:</strong> En la lección del 25 de marzo, estudiamos un teorema que permite determinar cuándo una matriz posee una única factorización LU. Dicho criterio establece que la factorización es única si y solo si todas las submatrices principales de la matriz son invertibles, es decir, si sus determinantes son distintos de cero.

Sin embargo, también es posible caracterizar la invertibilidad de una matriz en términos de su rango, según la siguiente proposición:

                            Proposición: Una matriz A ∈ ℝ^m×m es invertible si y solo si rango(A) = m.

Con base en esta proposición, implemente la función `tf = tieneUnicaFactLU(A)` en Python. Esta función debe determinar si la matriz A tiene una única factorización LU. En caso afirmativo, la función debe devolver `tf = 1`; en caso contrario, debe devolver `tf = 0`. Además, la función debe verificar que A sea una matriz cuadrada antes de proceder con los cálculos. Finalmente, pruebe la función con dos matrices de tamaño 5×5, donde una tenga una única factorización LU y la otra no.



In [2]:
import numpy as np

def tieneUnicaFactLU(A):
    # Verificar si la matriz es cuadrada
    if A.shape[0] != A.shape[1]:
        return 0
    
    n = A.shape[0]

    # Verificar determinantes de submatrices principales
    for k in range(1, n+1):
        submatriz = A[:k, :k]
        if np.linalg.det(submatriz) == 0:
            return 0

    return 1

# Pruebas con dos matrices 5x5
# Una con factorización LU única
A1 = np.array([[2, 3, 1, 5, 4],
               [4, 7, 2, 10, 8],
               [6, 2, 8, 9, 7],
               [1, 3, 2, 7, 6],
               [3, 6, 5, 8, 9]])

# Otra sin factorización LU única (ej. una fila depende de otras)
A2 = np.array([[1, 2, 3, 4, 5],
               [2, 4, 6, 8, 10],
               [3, 6, 9, 12, 15],
               [4, 8, 12, 16, 20],
               [5, 10, 15, 20, 25]])

# Resultados
print("A1 tiene única factorización LU:", tieneUnicaFactLU(A1))  # Debería devolver 1
print("A2 tiene única factorización LU:", tieneUnicaFactLU(A2))  # Debería devolver 0


A1 tiene única factorización LU: 1
A2 tiene única factorización LU: 0


<strong>Pregunta 2:</strong> En la lección del 27 de marzo, se explicó el método Thomas para resolver el sistema de ecuaciones $Ax = b$, donde A es una matriz tridiagonal. Dicha información se encuentra en el documento `metodo thomas.pdf`. Implemente en GNU Octave o Python el método de Thomas, creando una función de la forma `x=thomas(A,b)`, donde x es la solución del sistema $Ax = b$. Luego resuelva el problema que se encuentra en la página 5 del documento `metodo thomas.pdf.`


In [6]:
clc; clear; close all;

% Crear sistema tridiagonal
n = 100;
A = zeros(n);  % Inicializar matriz

for i = 1:n
    A(i,i) = 5;
    if i < n
        A(i,i+1) = 1;
        A(i+1,i) = 1;
    end
end

% Vector lado derecho
b = -14 * ones(n,1);
b(1) = -12;
b(n) = -12;


% ===========================
% Método de Thomas (entrada A, b)
% ===========================
function x = metodo_thomas(A, b)
    % Función newton_thomas: Método que permite aproximar la solución de ecuaciones no lineales (con el método Newton Raphson) la cual además da el tiempo de ejecución de la aproximación.
    % Entradas:
    %          A -> Matriz tridiagonal
    %          b -> Matriz columna 
    %
    % Salidas:
    %          x -> La solución del sistema Ax = b

    d = b;
    n = length(d);
    
    
    % Extraer vectores a, b, c de la matriz completa
    a = zeros(n, 1);   % a_1 = 0
    b = zeros(n, 1);
    c = zeros(n, 1);   % c_n = 0

    for i = 1:n
        b(i) = A(i, i);
        if i > 1
            a(i) = A(i, i-1);
        end
        if i < n
            c(i) = A(i, i+1);
        end
    end

    % Inicializar vectore p y q
    p = zeros(n-1, 1);
    q = zeros(n, 1);

    % Paso 1: cálculo de p y q
    p(1) = c(1) / b(1);
    q(1) = d(1) / b(1);

    for i = 2:n-1
        denom = b(i) - p(i-1) * a(i);
        p(i) = c(i) / denom;
    end

    for i = 2:n
        denom = b(i) - p(i-1) * a(i);
        q(i) = (d(i) - q(i-1) * a(i)) / denom;
    end

    % Paso 2: Solucion del sistema
    x = zeros(n, 1);
    x(n) = q(n);
    for i = n-1:-1:1
        x(i) = q(i) - p(i) * x(i+1);
    end
end

% ===========================
% Llamar al método
% ===========================
x = metodo_thomas(A, b);
disp("La solución del sistema (x) es:")
disp(x)


La solución del sistema (x) es:
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2
  -2


**Pregunta 3:** En la lección del 1° de abril, se explicó el método basado en la factorización $QR$ para resolver sistemas de ecuaciones. Sin embargo, no se explicó el método para obtener la factorización $QR$ de la matriz. En el documento `factorizacionQR.pdf` se explica el método basado en la ortogonalización de Gram-Schimidt para obtener la factorización $QR$ de una matriz $A$. Luego, implemente computacionalmente en Python dicho método, creando una función de la forma `[Q, R] = fact_qr(A)`, donde $A = QR$ es la factorización $QR$ de $A$. Luego, utilice dicha función para obtener la factorización $QR$ de la matriz:

$$
A = \begin{bmatrix}
2 & -1 & 3 & 0 & 1 & -2 & 4 & -3 & 5 & 6 \\
-3 & -2 & 1 & 5 & -4 & 3 & -1 & 6 & 2 & -7 \\
1 & -2 & -4 & 3 & 2 & 0 & 1 & 9 & -5 & 4 \\
4 & -3 & 1 & 2 & -5 & -1 & 0 & 8 & 9 & -6 \\
5 & 7 & -6 & 4 & 3 & 2 & 4 & 2 & 9 & 0 \\
6 & -4 & 5 & -2 & -7 & 3 & 2 & -1 & 0 & 8 \\
-7 & 9 & -6 & 1 & 4 & -8 & 0 & -2 & -3 & 1 \\
-8 & -2 & 4 & 7 & -9 & 10 & 1 & -5 & -6 & -7 \\
9 & 11 & -10 & 5 & 6 & -13 & -2 & -6 & 1 & 2 \\
10 & -8 & 9 & -11 & 12 & -14 & -3 & -7 & 8 & 7
\end{bmatrix}
$$


In [3]:
import numpy as np

def fact_qr(A):
    A = np.array(A, dtype=float)  # Convertir a float para evitar errores de tipo
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if R[j, j] == 0:
            raise ValueError("Las columnas de A son linealmente dependientes.")
        Q[:, j] = v / R[j, j]

    return Q, R

# Definición de la matriz A (10x10)
A = np.array([
    [2, -1, 3, 0, 1, -2, 4, -3, 5, 6],
    [-3, 5, -2, 1, 3, 0, -1, 4, -6, 7],
    [1, -2, 4, 5, -5, 7, 8, -9, 10, 11],
    [-4, -3, 1, -2, -5, 6, -7, 8, -9, 10],
    [5, 7, -6, 0, 3, -4, 2, -1, 6, -5],
    [6, -4, 5, -7, 8, 1, -3, 2, -9, 4],
    [-7, 9, -8, 3, -1, 2, 5, -4, 3, -6],
    [8, 2, -3, 6, 4, -5, 0, 1, 2, -7],
    [-9, 11, -10, 8, -12, 13, 6, 7, -5, -6],
    [10, -8, 9, -11, 12, -14, 15, -18, 7, -9]
])

# Cálculo de la factorización QR
Q, R = fact_qr(A)

# Mostrar resultados con formato
np.set_printoptions(precision=3, suppress=True)
print("Matriz Q:")
print(Q)

print("\nMatriz R:")
print(R)

# Verificación de que Q @ R ≈ A
print("\n¿Q @ R es aproximadamente igual a A?:", np.allclose(Q @ R, A))


Matriz Q:
[[ 0.102  0.01   0.406  0.155 -0.101 -0.241 -0.263  0.207  0.693  0.374]
 [-0.153  0.209  0.542 -0.087  0.42   0.07  -0.322  0.307 -0.483  0.14 ]
 [ 0.051 -0.091  0.446  0.623 -0.274  0.14   0.233 -0.409 -0.261  0.135]
 [-0.204 -0.338 -0.278 -0.14  -0.25   0.189 -0.073  0.113 -0.216  0.764]
 [ 0.255  0.63  -0.041 -0.267 -0.433 -0.087 -0.33  -0.344 -0.154  0.139]
 [ 0.306 -0.034  0.213 -0.281 -0.05   0.848  0.046  0.032  0.227 -0.07 ]
 [-0.357  0.316  0.092 -0.25   0.373  0.01   0.482 -0.409  0.237  0.326]
 [ 0.408  0.422 -0.376  0.457  0.299  0.141  0.18   0.299 -0.023  0.272]
 [-0.459  0.37   0.074  0.05  -0.497  0.095  0.33   0.508  0.021 -0.146]
 [ 0.51  -0.142  0.25  -0.369 -0.106 -0.355  0.531  0.222 -0.2    0.111]]

Matriz R:
[[ 19.621 -11.314  11.416  -9.53   17.226 -17.634   5.096 -13.2     8.154
   -4.536]
 [  0.     15.684 -13.825   8.682  -0.389   0.095   4.505   2.528   3.97
  -11.943]
 [  0.      0.      4.851  -2.302   3.291   0.54   10.535  -9.555   4.492
    8

**Pregunta 4.** En la lección del 6° de abril, se explicó el método iterativo de Gauss-Seidel para resolver sistemas de ecuaciones. Implemente en Python la función `gauss_seidel(A, b, x0, tol, max_iter)`, el cual recibe:

- `A`: la matriz de coeficientes.
- `b`: el vector del lado derecho.
- `x0`: un vector inicial para la solución.
- `tol`: tolerancia para el criterio de convergencia.
- `max_iter`: número máximo de iteraciones.

El método debe iterar hasta que se cumpla el criterio de convergencia:

$$
\|Ax^{(k)} - b\|_2 < \text{tol}
$$

o se alcance el número máximo de iteraciones. Utilice dicha implementación computacional para resolver el sistema $Ax = b$, donde:

- $A \in \mathbb{R}^{1000 \times 1000}$ es una matriz definida como:

$$
A(i,j) = \begin{cases}
1001 & \text{si } i = j \\
1 & \text{si } i \ne j
\end{cases}
$$

- $b \in \mathbb{R}^{1000}$ es un vector columna tal que $b = (1, 1, \dots, 1)^T \in \mathbb{R}^{1000}$.

Al ejecutar la función `gauss_seidel`, se debe indicar solo el error final en la ventana de comandos.

**Observación:** No se puede calcular la inversa de una matriz en la fórmula de Gauss-Seidel, sino resolver un sistema de ecuaciones usando sustitución hacia adelante, como se explicó en clases.


In [25]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-6, max_iter=100):
    """
    Resuelve el sistema Ax = b utilizando el método de Gauss-Seidel y retorna el error final.
    
    A       : matriz de coeficientes del sistema (1000x1000)
    b       : vector del lado derecho (tamaño 1000)
    tol     : tolerancia para la convergencia (por defecto 1e-6)
    max_iter: número máximo de iteraciones (por defecto 100)
    
    Retorna el error final en el sistema.
    """
    n = len(b)  # Tamaño del sistema
    x = x0.copy()  # Inicializar la solución con x0
    
    # Descomposición de A en L, D, U
    L = np.tril(A, -1)  # Submatriz triangular inferior (sin la diagonal)
    D = np.diag(np.diag(A))  # Matriz diagonal
    U = np.triu(A, 1)  # Submatriz triangular superior (sin la diagonal)

    for k in range(max_iter):
        # Calculando los nuevos valores de x(k+1)
        for i in range(n):
            sum_L = np.dot(L[i, :i], x[:i])  # Parte izquierda (con L)
            sum_U = np.dot(U[i, i+1:], x[i+1:])  # Parte derecha (con U y x(k))
            
            # Actualización del valor de x[i]
            x[i] = (b[i] - sum_L - sum_U) / D[i, i]
        
        # Verificar la convergencia: ||Ax - b|| < tol
        error = np.linalg.norm(np.dot(A, x) - b, 2)  # Norma L2 (euclidiana)
        
        if error < tol:  # Si el error es menor que la tolerancia, se alcanza la convergencia
            break
    
    return error  # Retorna el error final

# Crear la matriz A de tamaño 1000x1000
n = 1000
A = np.ones((n, n))  # Crear una matriz de unos
np.fill_diagonal(A, 1001)  # Rellenar la diagonal con 1001

# Crear el vector b
b = np.ones(n)  # Vector columna con todos los elementos iguales a 1

x0 = np.zeros(n)  # Inicializar el vector solución con ceros

# Resolver el sistema Ax = b y obtener el error
error = gauss_seidel(A, b, x0)

# Mostrar el error final en el sistema
print(f"Error final: {error}")


Error final: 3.578478339767923e-07


**Pregunta 5.** Esta pregunta se divide en 4 sub-preguntas, las cuales tienen la finalidad de implementar computacionalmente en GNU Octave el método de Jacobi para aproximar los valores propios de una matriz simétrica.

**a)** Implemente computacionalmente la función `theta = angulo(A, i, j)`, cuya salida es un número real `theta`, tal que:

$$
\theta = 
\begin{cases}
\frac{1}{2} \tan^{-1} \left( \frac{2A(i,j)}{A(i,i) - A(j,j)} \right), & \text{si } |A(i,i) - A(j,j)| > 10^{-16} \\
0, & \text{si } |A(i,i) - A(j,j)| \leq 10^{-16}
\end{cases}
$$

**b)** Implemente computacionalmente la función `G = matriz_rotacion(i, j, m, theta)`, cuya salida es una matriz \( G \in \mathbb{R}^{m \times m} \), tal que:

$$
G = I_m + Z,
$$

donde $I_m \in \mathbb{R}^{m \times m}$ es la matriz identidad, y $Z \in \mathbb{R}^{m \times m}$ es una matriz nula, menos en las siguientes entradas:

- $Z(i,i) = \cos(\text{theta}) - 1$
- $Z(j,j) = \cos(\text{theta}) - 1$
- $Z(i,j) = -\sin(\text{theta})$ (Solo se calcula si $i \ne j$)
- $Z(j,i) = \sin(\text{theta})$ (Solo se calcula si $i \ne j$)

**c)** Implemente computacionalmente la función:

```octave
[xk, ek] = jacobi_valores_propios(A, iterMax, tol)
```

el cual es el método de Jacobi para aproximar los valores propios de una matriz simétrica, donde:

- `A` es una matriz simétrica de tamaño \( m \times m \)
- `iterMax` son las iteraciones máximas, y `tol` es la tolerancia
- `xk` es un vector de tamaño \( m \) que tiene las aproximaciones de los valores propios de \( A \)
- `ek` es el criterio de error definido como \( ek = \|x_{k+1} - x_k\|_2 \)

El algoritmo del método de Jacobi se encuentra a continuación:

---
### Algoritmo 1: Método de Jacobi
---

**Entrada:**  
$A \in \mathbb{R}^{m \times m}$ simétrica, $\text{iterMax} \in \{1, 2, \dots\}$, $\text{tol} > 0$

**Salida:**  
$x_k \in \mathbb{R}^n$, $e_k > 0$

```text
1:  A₀ = A
2:  x₀ = diag(A₀)
3:  for k = 0, 1, …, iterMax do
4:      Bₖ = Aₖ
5:      for i = 1, 2, …, m do
6:          for j = 1, 2, …, m do
7:              θ = angulo(Bₖ, i, j)
8:              G = matriz_rotacion(i, j, m, θ)
9:              Bₖ = Gᵀ Bₖ G
10:         end for
11:     end for
12:     Aₖ₊₁ = Bₖ
13:     xₖ₊₁ = diag(Aₖ₊₁)
14:     eₖ = ‖xₖ₊₁ - xₖ‖₂
15:     if eₖ < tol then
16:         k = k + 1
17:         break
18:     end if
19: end for
```

---

**Nota:** El Algoritmo 1 genera una sucesión de vectores $\{x_k\}_{k=0}^{\infty}$ que converge a los valores propios de una matriz simétrica $A$.

---

**d)** En un archivo con nombre `prueba_jacobi`, aproxime los valores propios de la matriz simétrica $A \in \mathbb{R}^{15 \times 15}$, donde $A(i,j) = 0.5(i + j)$, para todo $i,j = 1, 2, \dots, 15$.  Para eso, utilice la función `jacobi_valores_propios` implementada en la pregunta anterior.  Cuando se ejecute este archivo, se debe imprimir en la ventana de comandos (consola) las salidas de la función `jacobi_valores_propios`.



In [4]:
% ===============================
% Función 1: angulo
% ===============================
function theta = angulo(A, i, j)
  if abs(A(i,i) - A(j,j)) > 1e-16
    theta = 0.5 * atan( (2 * A(i,j)) / (A(i,i) - A(j,j)) );
  else
    theta = 0;
  end
end

% ===============================
% Función 2: matriz_rotacion
% ===============================
function G = matriz_rotacion(i, j, m, theta)
    Z = zeros(m);  % matriz nula m x m

    % Entradas modificadas de Z
    Z(i,i) = cos(theta) - 1;
    Z(j,j) = cos(theta) - 1;

    if i ~= j
        Z(i,j) = -sin(theta);
        Z(j,i) = sin(theta);
    end

    % Matriz de rotación G = I + Z
    G = eye(m) + Z;
end


% ===============================
% Función 3: jacobi_valores_propios
% ===============================
function [xk, ek] = jacobi_valores_propios(A, iterMax, tol)
  m = size(A,1);
  A0 = A;
  x0 = diag(A0);
  Ak = A0;

  for k = 1:iterMax
    Bk = Ak;

    for i = 1:m
      for j = 1:m
        if i != j
          theta = angulo(Bk, i, j);
          G = matriz_rotacion(i, j, m, theta);
          Bk = G' * Bk * G;
        end
      end
    end

    Ak1 = Bk;
    xk = diag(Ak1);
    ek = norm(xk - x0, 2);
    if ek < tol
      break;
    end
    x0 = xk;
    Ak = Ak1;
  end
end

% ===============================
% Script principal: prueba_jacobi
% ===============================
% Crear matriz A de 15x15 tal que A(i,j) = 0.5*(i + j)
n = 15;
A = zeros(n);
for i = 1:n
  for j = 1:n
    A(i,j) = 0.5 * (i + j);
  end
end

% Ejecutar el método de Jacobi
iterMax = 100;
tol = 1e-6;
[xk, ek] = jacobi_valores_propios(A, iterMax, tol);

% Mostrar resultados
disp("Aproximación de los valores propios:");
disp(xk);
disp("Error final:");
disp(ek);


Aproximación de los valores propios:
  -8.1909e+00
   1.2819e+02
   3.2691e-15
   3.0521e-15
  -2.3401e-15
   1.8530e-15
   8.2087e-16
  -5.5273e-15
  -4.6490e-15
   6.1197e-16
  -1.4310e-16
   5.7583e-15
   6.0675e-17
  -1.0105e-15
   4.4646e-15
Error final:
1.7628e-15
